#!/bin/sh
R='\033[0;31m'
G='\033[0;32m'
Y='\033[1;33m'
C='\033[0;36m'
N='\033[0m'
clear
echo "${Y}Chkalov DK (Development Kit) installer"
echo ""
echo "${G}Downloading stable release for Linux..."
wget -q http://ftpmsga.narod.ws/stable/chkalov-linux.tar.gz -O /tmp/chkalov.tar.gz
echo "${N}"
