#include "parser.h"
#include "token.h"
#include "chkalov.h"
#include <stdio.h>
#include <iostream>
#include <cctype>
#include <cstring>
//#include <сstdlib>
#include <stdlib.h>

static Scope nullscope;

//const char* envi = getenv("CHKALOV");
Parser::Parser(const string &_fni, const string &_fn, bool _debug) : fn(_fn), p(0), debug(_debug) {
    string env=getenv("CHKALOV");
    ifstream a(env+"/imports-table.txt");
    if(!a) error("Imports table (" << env+"/imports-table.txt" << ") not found!")
    string sa, section;
    getline(a, sa);
    if(debug) cout << sa << '!' << endl;
    if(sa!="$DOCTYPE CHKALOV IMPORTS <1.00>") error("Imports table (imports-table.txt) corrupted! Finded : " << sa << '!');
    while(!a.eof()) {
        getline(a, sa);
        if(debug) cout << sa << '!' << endl;
        if(sa[0]=='%') {
            section=sa.substr(1);
            imports.push_back(Import(sa.substr(1)));
        } else if(sa[0]=='+') {
            for(uint64_t i=0LL; i<imports.size(); i++) {
                if(section==imports[i].name) imports[i].add(sa.substr(1, sa.find(",")-1), atoll(sa.substr(sa.find(",")).c_str()));
                else error("Unimported function: " << sa.substr(1) << " , section : " << section << '!' << sa);
                cout << atoll(sa.substr(sa.find(",")).c_str()) << '!' << endl;
            }
        };
        if(debug) cout << "Section: " << section << " , function: " << sa << '!' << endl;
    }
    a.close();
    a.open(_fni, ios::in);
    string x;
    if(debug) {
        for(uint64_t i=0; i<imports.size(); i++) {
            cout << "Name: " << imports[i].name << " , functions: ";
            for(uint64_t j=0; j<imports[i].funcs.size(); j++) cout << ' ' << imports[i].funcs[j].name << " | ";
        }
        cout << '!' << endl;
    }
    while(!a.eof()) {
        getline(a, x);
        parse(x);
        if(debug) cout << "AA! " << x << '!' << endl;
    }
    a.close();
}

void Parser::render(Vm vm) {
    code.push_back(vm.opcode);
    code.push_back(vm.type);
    size_t sz=st[vm.type];
    int64_t v=vm.value;
    unsigned char *p=(unsigned char*)&v;
    for(int i=0;i<sz;i++) code.push_back(p[i]);
}

size_t Parser::addPool(Pool _pool) {
    pool.push_back(_pool);
    return pool.size()-1;
}

void Parser::finally() {
    /* ... */
    ofstream o(fn, ios::binary);
    uint32_t magic=0x05020100;
    uint64_t size=0, i, a, b, c; // 4 + 5 + 5 = 14 !!!!!
    o.write(_CP &magic, sizeof(uint32_t)); ///// 0 2 1 5     9 0 0 0 0 10 0 0 0 0
    size=pool.size();
    o.write(_TPL size, sz(size));
    for(i=0; i<size; i++) {
        o.write(_CP &pool[i].type, sz(char));
        a=pool[i].value.size();
        o.write(_TPL a, sz(a));
        o.write(pool[i].value.data(), pool[i].value.size());
    }
    if(debug) {
        cout << "=== GENERATED BYTECODE ===" << endl;
        for(size_t i = 0; i < code.size(); i++) {
            cout << "[" << i << "] : 0x" << hex << (int)code[i] << dec << endl;
        }
        cout << "=== END BYTECODE ===" << endl;
    }
    size=code.size();
    o.write(_TPL size, sz(size));
    o.write(_CP code.data(), size);
    if(debug) cout << sizeof(Vm) << endl;
    o.close();
}

void Parser::parse(const string &line) {
    uint64_t pos=0;
    while(pos < line.length()) {
        if(debug) cout << "I" << '!' << endl;
        while(pos < line.length() && isspace(line[pos])) pos++;

        if(pos >= line.length()) file.push_back(Token(ENOF));

        if(line.substr(pos, 3) == "var") { // обычная переменная
            pos+=3;
            file.push_back(Token(VAR, "var"));
            continue;
        }

        if(line.substr(pos, 6)=="import") {
            pos+=6;
            file.push_back(Token(IMPORT, "import"));
            continue;
        }

        if(line.substr(pos, 2)=="if") {
            pos+=2;
            file.push_back(Token(IF, "if"));
            continue;
        }

        if(line.substr(pos, 2)=="==") {
            pos+=2;
            file.push_back(Token(EQ, "=="));
            if(debug) cout << "eq!" << endl;
            continue;
        }

        if(line.substr(pos, 2)=="!=") {
            pos+=2;
            file.push_back(Token(NEQ, "=="));
            if(debug) cout << "neq!" << endl;
            continue;
        }

        /*if(line.substr(pos, 2)==">=") {
            pos+=2;
            file.push_back(Token(EQ, "=="));
            if(debug) cout << "eq!" << endl;
            continue;
        }

        if(line.substr(pos, 2)=="<=") {
            pos+=2;
            file.push_back(Token(EQ, "=="));
            if(debug) cout << "eq!" << endl;
            continue;
        }*/

        if(isalpha(line[pos])) { // ID
            size_t start = pos;
            while(pos < line.length() && isalnum(line[pos])) pos++;
            string id = line.substr(start, pos - start);
            file.push_back(Token(ID, id));
            continue;
        }

        if(isdigit(line[pos])) { // число
            size_t start = pos;
            while(pos < line.length() && isdigit(line[pos])) pos++;
            string num = line.substr(start, pos - start);
            file.push_back(Token(NUMBER, num));
            continue;
        }

        if(line[pos]=='\"') { // строка
            size_t start=++pos;
            while(pos<line.length()&&line[pos]!='\"') pos++;
            string str=line.substr(start, pos-start);
            pos++;
            file.push_back(Token(STRING, str));
            continue;
        }

        /*if(line[pos]=='?') { // преобразование типа
            while(isspace(line[++pos]));
            if(line.substr(start, pos-start)=="Int") {
                while(isspace(line[++pos]));
                Token ni=file[++i];
                if(ni.type==ID) {

                }
            }
        }*/

        char c = line[pos++];
        switch(c) {
            case '=':
                file.push_back(Token(ASSIGN, "="));
                if(debug) cout << "assign!" << endl;
                break;
            case '+':
                file.push_back(Token(PLUS, "+"));
                break;
            case '-':
                file.push_back(Token(MINUS, "-"));
                break;
            case '*':
                file.push_back(Token(STAR, "*"));
                break;
            case '/':
                file.push_back(Token(SLASH, "/"));
                break;
            case '{':
                file.push_back(Token(LPAREN, "{"));
                break;
            case '}':
                file.push_back(Token(RPAREN, "}"));
                break;
            case ':':
                file.push_back(Token(COLON, ":"));
                break;
            case '@':
                file.push_back(Token(LCALL, "@"));
                break;
            case '(':
                file.push_back(Token(LBRACE, "("));
                break;
            case ')':
                file.push_back(Token(RBRACE, ")"));
                break;
        }
    }
}

void Parser::parseInstruction() {
    Token t;
    if(debug) cout << "A! Iteration : " << p << '!' << endl;
    t=file[p];
    switch(t.type) {
        case LPAREN: {
            scopes.enterScope();
            parseBlock();
            break;
        }
        case RPAREN: {
            scopes.exitScope();
            break;
        }
        case LCALL: {
            Token method=file[++p];
            if(method.type!=ID) error("Expected name function!");
            Token ntam=file[++p];
            if(ntam.type!=LBRACE) error("expected (!, detected : " << ntam.type);
            Token va=file[++p];
            if(va.type!=STRING) error("expected string!");
            ntam=file[++p];
            if(ntam.type!=RBRACE) error("expected )!, detected : " << ntam.type);
            for(uint64_t i=0; i<imports.size(); i++) {
                if(imports[i].contains(method.value)) {
                    if(debug) cout << "Calling: " << imports[i].name << '.' << method.value << '!' << endl;
                    pool.push_back({STR, va.value});
                    render({PUSH, STR, pool.size()-1});
                    pool.push_back({LIBRARY, imports[i].name+"."+method.value});
                    render({CALL, LIBRARY, pool.size()-1});
                } else error("Undefined function: " << method.value);
            }
            break;
        }
        case IMPORT: {
            Token libname=file[++p];
            if(libname.type!=ID) error("Expected name function!");
            imports.push_back(Import(libname.value));
            break;
        }
        case FUN: {
            Token funcname=file[++p];
            if(file[++p].type!=LPAREN) error("Expected {!");
            break;
        }
        case IF: {
            parseIf();
            break;
        }
    }
}

void Parser::parseFile() {
    for(p=0; p<file.size(); p++) {
        parseInstruction();
    }
};

VarType Parser::stringToType(string value) {
	if(value.substr(0, 3)=="Int") return VINT;
	if(value.substr(0, 5)=="String") return VSTRING;
	return VNOT;
}

bool Import::contains(string a) {
    for(uint64_t i=0; i<funcs.size(); i++) {
        if(a==funcs[i].name) return true;
    }
    return false;
}

void Import::add(string a, uint64_t _a) {
    funcs.push_back({a,_a});
}

void Parser::parseIf() {
    if(file[++p].type!=LBRACE) {
        error("Expected ( after if!");
    }
    scopes.enterScope();
    p++;
    Token x=file[p++], y=file[p++], z=file[p++];
    if(debug) cout << "x: " << x.value << " y: " << y.value << " z: "  << z.value << '!' << endl;
    Vm u, o;
    if(x.type==ID) u={LOAD, scopes.getVar(x.value).id}; else u={PUSH, seltype(atoll(x.value.c_str()))};
    if(z.type==ID) o={LOAD, scopes.getVar(z.value).id}; else o={PUSH, atoll(z.value.c_str())};
    switch(y.type) {
        case EQ: {
            render(u);
            render(o);
            uint64_t cs=code.size();
            render({IFNE, ADDR, 0});
            if(debug) cout << " CS: " << cs << '!' << endl;
            parseBlock();
            if(debug) cout << " code.size(): " << code.size() << '!' << endl;
            uint64_t tar=code.size();
            memcpy(code.data()+cs, &tar, sz(tar));
            break;
        }
        case NEQ: {
            //render({PUSH, seltype(atoll(x.value.c_str()))});
            //render({PUSH, seltype(atoll(z.value.c_str()))});
            render({IFE, ADDR, 0});
            uint64_t cs=code.size()-1;
            if(debug) cout << " CS: " << cs << '!' << endl;
            parseBlock();
            if(debug) cout << " code.size(): " << code.size() << '!' << endl;
            break;
        }
    }
}

void Parser::parseBlock() {
    Token t;
    while(t.type!=RPAREN) {
        if(debug) cout << "parseBlock!";
        t=file[p++];
        if(debug) cout << "t.type : " << t.type << " t.value : " << t.value << '!' << endl;
        parseInstruction();
    }
    scopes.exitScope();
}
